modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="coremod"
version="${file.jarVersion}"
displayName="Core Mod"
description='''
A powerful core block mod for Minecraft 1.20.1
Adds a 2x2 core block with infinite storage, crafting, and AE2/RS integration
'''
authors="CoreMod Team"
credits="Inspired by Applied Energistics 2"

[[dependencies.coremod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.coremod]]
modId="jei"
mandatory=false
versionRange="[12.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.coremod]]
modId="appliedenergistics2"
mandatory=false
versionRange="[12.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.coremod]]
modId="refinedstorage"
mandatory=false
versionRange="[1.12.0,)"
ordering="NONE"
side="BOTH"